# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='build_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='room_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='endtime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='starttime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
