# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0002_auto_20170831_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='build_id',
            new_name='build',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seat_id',
            new_name='seat',
        ),
    ]
