# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0014_auto_20170831_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
    ]
