# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0015_auto_20170831_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
