# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0016_auto_20170831_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='password',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='username',
        ),
        migrations.AddField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whu_seat_get.Person'),
        ),
    ]
