# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0020_auto_20170901_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='build',
            field=models.CharField(choices=[('1', '信息科学分馆'), ('2', '工学分馆'), ('3', '医学分馆')], max_length=50, null=True),
        ),
    ]
