# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0022_auto_20170901_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whu_seat_get.Person'),
        ),
    ]
