# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0023_auto_20170901_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
