# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0025_auto_20170901_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='build',
            field=models.CharField(choices=[('1', '信息科学分馆'), ('2', '工学分馆'), ('3', '医学分馆')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 2), null=True),
        ),
    ]
