# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whu_seat_get', '0026_auto_20170901_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 9), null=True),
        ),
    ]
